---
- name: Install AWS CLI
  become: yes
  pip:
      state: latest
      name:
          - "pip"
          - "awscli"
  when: aws_cli_install

- name: Test AWS CLI
  become: no
  command: aws --version
  when: aws_cli_install

- name: Download AWS ECS CLI
  become: yes
  get_url:
      url: "https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest"
      dest: "/usr/local/bin/ecs-cli"
      mode: 0555
  when: aws_ecs_cli_install

- name: Test AWS ECS CLI
  become: no
  command: ecs-cli --version
  when: aws_ecs_cli_install

- name: Install AWS Shell
  become: yes
  pip:
      state: latest
      name:
          - "pip"
          - "aws-shell"
  when: aws_shell_install

